"""initial

Revision ID: 5c95fc606542
Revises: 
Create Date: 2018-05-12 23:38:42.181467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c95fc606542'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('url_id', sa.String(length=32), nullable=False),
    sa.Column('tracks_str', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_name'), 'playlist', ['name'], unique=True)
    op.create_index(op.f('ix_playlist_url_id'), 'playlist', ['url_id'], unique=True)
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('artists', sa.String(length=64), nullable=False),
    sa.Column('album', sa.String(length=64), nullable=False),
    sa.Column('spot_id', sa.String(length=64), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spot_id')
    )
    op.create_index(op.f('ix_track_name'), 'track', ['name'], unique=True)
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrase_name'), 'phrase', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrase_name'), table_name='phrase')
    op.drop_table('phrase')
    op.drop_index(op.f('ix_track_name'), table_name='track')
    op.drop_table('track')
    op.drop_index(op.f('ix_playlist_url_id'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_name'), table_name='playlist')
    op.drop_table('playlist')
    # ### end Alembic commands ###
